#!/bin/bash
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# Platform Power Monitoring Setup
# Automatically detects and configures permissions for RAPL powercap files

set -e

GROUP_NAME="powercap"
CURRENT_USER="${SUDO_USER:-$USER}"
SYSFS_CONF="/etc/sysfs.d/powercap.conf"

echo "=== Platform Power Monitoring Setup ==="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This script must be run as root (use sudo)"
    exit 1
fi

# Step 1: Create powercap group if it doesn't exist
echo "[1/3] Checking group '$GROUP_NAME'..."
if getent group "$GROUP_NAME" > /dev/null 2>&1; then
    echo "  ✓ Group '$GROUP_NAME' already exists"
else
    echo "  Creating group '$GROUP_NAME'..."
    groupadd "$GROUP_NAME"
    echo "  ✓ Group created"
fi

# Step 2: Add current user to powercap group if not already a member
echo "[2/3] Checking user '$CURRENT_USER' group membership..."
USER_JUST_ADDED=false
if id -nG "$CURRENT_USER" | grep -qw "$GROUP_NAME"; then
    echo "  ✓ User '$CURRENT_USER' already in group '$GROUP_NAME'"
else
    echo "  Adding user '$CURRENT_USER' to group '$GROUP_NAME'..."
    usermod -aG "$GROUP_NAME" "$CURRENT_USER"
    echo "  ✓ User added to group"
    USER_JUST_ADDED=true
fi

# Step 3: Auto-detect all powercap energy_uj files and create sysfs configuration
echo "[3/3] Detecting powercap files and configuring permissions..."

# Detect all energy_uj files using shell globbing (works better with restricted directory permissions)
# Skip paths containing 'device/' or 'subsystem/' as these are symlinks creating circular references
declare -A seen_inodes
ENERGY_FILES_RAW=""

for control_type in /sys/class/powercap/*; do
    if [ ! -d "$control_type" ]; then
        continue
    fi
    
    # Find energy_uj files recursively using shell patterns
    # This handles intel-rapl:X and intel-rapl:X:Y patterns
    for pattern in "$control_type"/*/energy_uj "$control_type"/*/*/energy_uj "$control_type"/*/*/*/energy_uj; do
        # Skip if file doesn't exist or path contains symlink directories
        if [ ! -e "$pattern" ]; then
            continue
        fi
        
        # Skip paths with 'device/' or 'subsystem/' (symlinks causing duplicates)
        case "$pattern" in
            */device/* | */subsystem/*) continue ;;
        esac
        
        # Get inode number to deduplicate files (same file accessible via different symlink paths)
        inode=$(stat -c '%i' "$pattern" 2>/dev/null)
        if [ -n "$inode" ] && [ -z "${seen_inodes[$inode]}" ]; then
            seen_inodes[$inode]=1
            ENERGY_FILES_RAW="$ENERGY_FILES_RAW$pattern"$'\n'
        fi
    done
done

# Remove trailing newline and sort
ENERGY_FILES=$(echo "$ENERGY_FILES_RAW" | grep -v '^$' | sort)

if [ -z "$ENERGY_FILES" ]; then
    echo "  WARNING: No powercap energy_uj files found"
    echo "  Your system may not support RAPL power monitoring"
    exit 0
fi

FILE_COUNT=$(echo "$ENERGY_FILES" | wc -l)
echo "  Detected $FILE_COUNT powercap energy files"

# Create sysfs.d directory
mkdir -p /etc/sysfs.d

# Generate sysfs configuration dynamically
cat > "$SYSFS_CONF" << 'SYSFS_HEADER'
# Intel RAPL powercap permissions - auto-generated
# Allows powercap group to read energy consumption data
# Generated by Platform Power Monitoring setup script

SYSFS_HEADER

# Add configuration for each detected file
for file in $ENERGY_FILES; do
    # Convert /sys/class/powercap/path/to/file to class/powercap/path/to/file
    sysfs_path="${file#/sys/}"
    
    echo "mode $sysfs_path = 0440" >> "$SYSFS_CONF"
    echo "owner $sysfs_path = root:$GROUP_NAME" >> "$SYSFS_CONF"
    
    # Apply permissions immediately for current session
    chown root:"$GROUP_NAME" "$file" 2>/dev/null || true
    chmod 0440 "$file" 2>/dev/null || true
done

echo "  ✓ Configuration written to $SYSFS_CONF"
echo "  ✓ Permissions applied to current session"

# Check if user needs to re-login
echo ""
echo "=== Setup Complete ==="
echo ""

# Check if current shell has the new group membership
VERIFY_CMD="cat /sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj"

# Check if user is in group in /etc/group
if ! groups "$CURRENT_USER" 2>/dev/null | grep -qw "$GROUP_NAME"; then
    echo "Group membership setup incomplete"
    echo "  Please re-run this script"
    echo ""
    exit 1
fi

SHELL_HAS_GROUP=false

if [ -n "$SUDO_USER" ]; then
    if [ "$USER_JUST_ADDED" = true ]; then
        SHELL_HAS_GROUP=false
    else
        if [ -n "$ENERGY_FILES" ]; then
            FIRST_FILE=$(echo "$ENERGY_FILES" | head -1)
            if sudo -u "$CURRENT_USER" -i test -r "$FIRST_FILE" 2>/dev/null; then
                SHELL_HAS_GROUP=true
            fi
        fi
    fi
else
    SHELL_HAS_GROUP=false
fi

# Display appropriate message
if [ "$SHELL_HAS_GROUP" = true ]; then
    echo "✓ Group membership active - you can access powercap files"
    echo ""
    echo "Test it now:"
    echo "  $VERIFY_CMD"
else
    echo "✓ Setup complete - group membership configured"
    echo ""
    echo "IMPORTANT: Your current shell session needs group activation"
    if [ "$USER_JUST_ADDED" = true ]; then
        echo "  (User was just added to '$GROUP_NAME' group)"
    else
        echo "  (Group membership exists but not loaded in current session)"
    fi
    echo ""
    echo "Choose one option to activate:"
    echo ""
    echo "  Option 1 - New shell with group active (RECOMMENDED):"
    echo "    newgrp $GROUP_NAME"
    echo "    # This starts a new shell with the group loaded"
    echo "    # Type 'exit' when done to return to original shell"
    echo ""
    echo "  Option 2 - Logout and login again (or reboot)"
    echo ""
    echo "After activation, verify access:"
    echo "  $VERIFY_CMD"
fi

echo ""
