#!/bin/bash
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# System Setup
# Configures system settings required for full functionality.
# New modules can be added to this script without requiring documentation updates.
#
# Usage:
#   sudo bash system-setup.sh    Run all modules (recommended)
#   bash system-setup.sh         Run modules that do not require root

CURRENT_USER="${SUDO_USER:-$USER}"
_MODULE_PASS=()
_MODULE_SKIP=()
_MODULE_FAIL=()

_is_root() { [ "$EUID" -eq 0 ]; }

# ---------------------------------------------------------------------------
# Module 1: Platform Power Monitoring
# ---------------------------------------------------------------------------
setup_powercap() {
    local MODULE="Platform Power Monitoring"
    echo ""
    echo "--- $MODULE ---"

    if ! _is_root; then
        echo "  [SKIP] Root required. Re-run with sudo to configure this module."
        _MODULE_SKIP+=("$MODULE")
        return 0
    fi

    # Check if RAPL is available on this system
    local has_rapl=false
    local control_type
    for control_type in /sys/class/powercap/*; do
        [ -d "$control_type" ] && has_rapl=true && break
    done
    if [ "$has_rapl" = false ]; then
        echo "  [WARN] No powercap devices detected (RAPL may not be supported on this system)"
        _MODULE_SKIP+=("$MODULE (no RAPL files)")
        return 0
    fi

    # Remove stale sysfsutils config from the old group-based approach.
    # That config (generated by setup-powercap-permissions.sh) sets mode 0440 at boot
    # via sysfsutils.service, which runs AFTER udev and overrides the udev chmod o+r,
    # leaving the main zone energy_uj file at 0440 (not world-readable).
    if [ -f /etc/sysfs.d/powercap.conf ]; then
        rm -f /etc/sysfs.d/powercap.conf
        echo "  [OK] Removed stale /etc/sysfs.d/powercap.conf (old group-based config)"
    fi

    # Write udev rule — fires at actual boot when the kernel generates real 'add' events
    # for powercap devices (persistent, no group membership or logout required).
    # Note: udevadm trigger (synthetic events) cannot activate RUN+= for intel-rapl zone
    # devices because their sysfs uevent file is kernel-write-protected even for root.
    # Real kernel boot events are NOT affected by this restriction.
    local UDEV_RULE_FILE="/etc/udev/rules.d/90-powercap.rules"
    mkdir -p /etc/udev/rules.d
    cat > "$UDEV_RULE_FILE" << 'UDEV_EOF'
# RAPL powercap energy counter read access - auto-generated by system-setup.sh
# Grants all users read-only access to energy_uj counters on each boot.
SUBSYSTEM=="powercap", ATTR{energy_uj}!="", ACTION=="add", RUN+="/bin/chmod o+r /sys%p/energy_uj"
UDEV_EOF
    udevadm control --reload-rules 2>/dev/null || true
    echo "  [OK] udev rule written to $UDEV_RULE_FILE (active on every boot)"

    # Apply permissions to the current session immediately via direct chmod.
    # udevadm trigger cannot synthesize 'add' events for intel-rapl zone devices
    # (their uevent sysfs files are kernel-write-protected), so chmod directly instead.
    # /sys/class/powercap/*/energy_uj covers all zones via the flat class symlinks.
    # Uses shell glob because find does not traverse sysfs correctly.
    local energy_file chmod_count=0
    for energy_file in /sys/class/powercap/*/energy_uj; do
        [ -e "$energy_file" ] || continue
        if chmod o+r "$energy_file" 2>/dev/null; then
            chmod_count=$((chmod_count + 1))
        fi
    done
    if [ "$chmod_count" -gt 0 ]; then
        echo "  [OK] Permissions applied to $chmod_count energy_uj file(s) in current session"
    else
        echo "  [WARN] Could not apply permissions to any energy_uj files"
    fi

    # Verify access as the calling user
    local FIRST_FILE=""
    local control_type2 pattern2
    for control_type2 in /sys/class/powercap/*; do
        [ ! -d "$control_type2" ] && continue
        for pattern2 in "$control_type2"/*/energy_uj "$control_type2"/*/*/energy_uj; do
            [ ! -e "$pattern2" ] && continue
            case "$pattern2" in */device/* | */subsystem/*) continue ;; esac
            FIRST_FILE="$pattern2"
            break 2
        done
    done

    if [ -n "$FIRST_FILE" ]; then
        local CALLING_USER="${SUDO_USER:-}"
        if [ -n "$CALLING_USER" ]; then
            if sudo -u "$CALLING_USER" test -r "$FIRST_FILE" 2>/dev/null; then
                echo "  [OK] Powercap files are readable by '$CALLING_USER' without root"
            else
                echo "  [WARN] Verification failed for '$CALLING_USER'"
                echo "         Verify manually: cat $FIRST_FILE"
            fi
        else
            if test -r "$FIRST_FILE" 2>/dev/null; then
                echo "  [OK] Powercap files are readable without root"
            fi
        fi
    fi

    _MODULE_PASS+=("$MODULE")
}


# ---------------------------------------------------------------------------
# Module 2: Memory DIMM Information
# ---------------------------------------------------------------------------
setup_memory_dimm() {
    local MODULE="Memory DIMM Information"
    echo ""
    echo "--- $MODULE ---"

    if ! _is_root; then
        echo "  [SKIP] Root required. Re-run with sudo to configure this module."
        _MODULE_SKIP+=("$MODULE")
        return 0
    fi

    # Verify required tools
    local tool MISSING_TOOLS=false
    for tool in setcap getcap; do
        if ! command -v "$tool" > /dev/null 2>&1; then
            echo "  [ERROR] '$tool' not found. Install: sudo apt-get install libcap2-bin"
            MISSING_TOOLS=true
        fi
    done
    if [ "$MISSING_TOOLS" = true ]; then
        _MODULE_FAIL+=("$MODULE (install libcap2-bin and dmidecode, then re-run)")
        return 1
    fi

    # Locate dmidecode
    local DMIDECODE_PATH="" candidate
    for candidate in /usr/sbin/dmidecode /sbin/dmidecode /usr/bin/dmidecode; do
        if [ -x "$candidate" ]; then
            DMIDECODE_PATH="$candidate"
            break
        fi
    done
    [ -z "$DMIDECODE_PATH" ] && DMIDECODE_PATH=$(command -v dmidecode 2>/dev/null || true)
    if [ -z "$DMIDECODE_PATH" ]; then
        echo "  [ERROR] dmidecode not found. Install: sudo apt-get install dmidecode"
        _MODULE_FAIL+=("$MODULE (install dmidecode, then re-run)")
        return 1
    fi
    echo "  [OK] Found dmidecode at: $DMIDECODE_PATH"

    # Check existing capability
    local CURRENT_CAPS NEW_CAPS
    CURRENT_CAPS=$(getcap "$DMIDECODE_PATH" 2>/dev/null || true)
    if printf '%s' "$CURRENT_CAPS" | grep -q "cap_dac_read_search"; then
        echo "  [OK] cap_dac_read_search already set: $CURRENT_CAPS"
    fi

    # Apply capability
    setcap cap_dac_read_search+ep "$DMIDECODE_PATH" || { echo "  [ERROR] setcap failed"; _MODULE_FAIL+=("$MODULE"); return 1; }
    NEW_CAPS=$(getcap "$DMIDECODE_PATH" 2>/dev/null || true)
    echo "  [OK] Capability applied: $NEW_CAPS"
    echo "  [NOTE] Re-run this script after dmidecode package updates (upgrades reset capabilities)"

    # Verify
    local CALLING_USER="${SUDO_USER:-}"
    if [ -n "$CALLING_USER" ]; then
        if sudo -u "$CALLING_USER" "$DMIDECODE_PATH" -t 16,17 > /dev/null 2>&1; then
            echo "  [OK] dmidecode can read memory DIMM information without root"
        else
            echo "  [WARN] Verification failed for '$CALLING_USER' (AppArmor/SELinux may restrict access)"
            echo "         Verify manually: dmidecode -t 16,17"
        fi
    else
        if "$DMIDECODE_PATH" -t 16,17 > /dev/null 2>&1; then
            echo "  [OK] dmidecode can read memory DIMM information without root"
        else
            echo "  [WARN] Verification failed. Try: dmidecode -t 16,17"
        fi
    fi

    _MODULE_PASS+=("$MODULE")
}

# ---------------------------------------------------------------------------
# Module 3: GPU Engine Performance Metrics (perf_event_paranoid)
# ---------------------------------------------------------------------------
setup_gpu_perf_events() {
    local MODULE="GPU Engine Performance Metrics"
    echo ""
    echo "--- $MODULE ---"

    if ! _is_root; then
        echo "  [SKIP] Root required. Re-run with sudo to configure this module."
        _MODULE_SKIP+=("$MODULE")
        return 0
    fi

    # perf_event_paranoid controls which users can open Linux perf events.
    # The xe and i915 GPU drivers expose per-engine utilisation counters
    # (engine-active-ticks / engine-total-ticks) via their device PMU.
    # These events measure system-wide GPU state and always use pid=-1
    # (system-wide mode), which requires perf_event_paranoid <= 0.
    #
    # Paranoia levels:
    #   -1  No restrictions (not recommended)
    #    0  Hardware/device PMU events for all users, including system-wide
    #       (xe/i915 GPU engine utilisation requires this level)
    #       Kernel-space tracing is still restricted to root/CAP_PERFMON.
    #    1  Per-process software events only for unprivileged users
    #       (NOT sufficient for system-wide GPU device PMU events)
    #    2  Software events only (many distro defaults)
    #    3+ Block tracing / eBPF helpers (Ubuntu hardened default; value 4 on some)
    #
    # Setting 0 is used by Fedora workstation defaults and allows xe/i915 GPU
    # engine PMU access without enabling the more security-sensitive kernel-space
    # tracing or sampling capabilities.
    local TARGET_PARANOID=0
    local SYSCTL_FILE="/etc/sysctl.d/90-esq-perf.conf"

    # Check current value
    local CURRENT_PARANOID
    CURRENT_PARANOID=$(cat /proc/sys/kernel/perf_event_paranoid 2>/dev/null || echo "unknown")
    echo "  [INFO] Current perf_event_paranoid: $CURRENT_PARANOID"

    if [ "$CURRENT_PARANOID" != "unknown" ] && [ "$CURRENT_PARANOID" -le "$TARGET_PARANOID" ] 2>/dev/null; then
        echo "  [OK] perf_event_paranoid ($CURRENT_PARANOID) is already <= $TARGET_PARANOID"
        # Still write/verify the sysctl.d file for persistence
    fi

    # Write sysctl.d drop-in for persistence across reboots.
    # Uses a drop-in under /etc/sysctl.d/ so it survives package upgrades.
    mkdir -p /etc/sysctl.d
    cat > "$SYSCTL_FILE" << 'SYSCTL_EOF'
# GPU engine-level performance metrics via Linux perf PMU
# Required for xe/i915 engine-active-ticks / engine-total-ticks events.
# These GPU device PMU events use system-wide (pid=-1) mode and require
# perf_event_paranoid <= 0 for unprivileged access.
# Value 0: system-wide hardware/device PMU events for all users;
#          kernel-space tracing still requires root/CAP_PERFMON.
# Auto-generated by system-setup.sh — do not edit manually.
kernel.perf_event_paranoid = 0
SYSCTL_EOF
    echo "  [OK] Wrote persistent config: $SYSCTL_FILE"

    # Apply to the current session immediately (no reboot required).
    if sysctl -w kernel.perf_event_paranoid="$TARGET_PARANOID" > /dev/null 2>&1; then
        echo "  [OK] Applied perf_event_paranoid=$TARGET_PARANOID to current session"
    else
        echo "  [WARN] sysctl write failed; setting will take effect after reboot"
        _MODULE_FAIL+=("$MODULE (sysctl write failed)")
        return 1
    fi

    # Verify: try to open a xe or i915 PMU file descriptor as the calling user.
    local CALLING_USER="${SUDO_USER:-}"
    local pmu_type_file
    # Look for the first xe PMU, fall back to i915
    for pmu_type_file in /sys/bus/event_source/devices/xe_*/type \
                         /sys/bus/event_source/devices/i915/type; do
        [ -f "$pmu_type_file" ] && break
    done

    if [ ! -f "$pmu_type_file" ]; then
        echo "  [INFO] No Intel GPU PMU devices found on this system"
        echo "         (xe/i915 GPU driver not loaded or no Intel GPU present)"
        _MODULE_PASS+=("$MODULE (no GPU PMU on this system)")
        return 0
    fi

    # Quick functional test: try perf stat with the discovered PMU type.
    # Use 'perf stat -e {type}/event=0x1/' for a single sample.
    local PMU_NAME
    PMU_NAME=$(basename "$(dirname "$pmu_type_file")")
    if [ -n "$CALLING_USER" ]; then
        if sudo -u "$CALLING_USER" perf stat -e "${PMU_NAME}/event=0x1/" \
                -a sleep 0 > /dev/null 2>&1; then
            echo "  [OK] GPU PMU events accessible as '$CALLING_USER' (${PMU_NAME})"
        else
            echo "  [INFO] perf functional test inconclusive for '$CALLING_USER'"
            echo "         Verify manually: perf stat -e ${PMU_NAME}/event=0x1/ sleep 0"
        fi
    else
        if perf stat -e "${PMU_NAME}/event=0x1/" -a sleep 0 > /dev/null 2>&1; then
            echo "  [OK] GPU PMU events accessible (${PMU_NAME})"
        else
            echo "  [INFO] perf functional test inconclusive"
            echo "         Verify manually: perf stat -e ${PMU_NAME}/event=0x1/ sleep 0"
        fi
    fi

    _MODULE_PASS+=("$MODULE")
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
    echo "=== System Setup ==="
    echo "Running as: $CURRENT_USER"

    setup_powercap
    setup_memory_dimm
    setup_gpu_perf_events

    echo ""
    echo "=== Summary ==="
    local m
    if [ ${#_MODULE_PASS[@]} -gt 0 ]; then
        for m in "${_MODULE_PASS[@]}"; do echo "  [OK]   $m"; done
    fi
    if [ ${#_MODULE_SKIP[@]} -gt 0 ]; then
        for m in "${_MODULE_SKIP[@]}"; do echo "  [SKIP] $m"; done
    fi
    if [ ${#_MODULE_FAIL[@]} -gt 0 ]; then
        for m in "${_MODULE_FAIL[@]}"; do echo "  [FAIL] $m"; done
    fi
    echo ""
    if [ ${#_MODULE_FAIL[@]} -eq 0 ]; then
        echo "Setup complete."
    else
        echo "Setup complete with errors. Review the output above."
        return 1
    fi
}

main "$@"
