#!/bin/bash
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# System Setup
# Configures system settings required for full functionality.
# New modules can be added to this script without requiring documentation updates.
#
# Usage:
#   sudo bash system-setup.sh    Run all modules (recommended)
#   bash system-setup.sh         Run modules that do not require root

CURRENT_USER="${SUDO_USER:-$USER}"
_MODULE_PASS=()
_MODULE_SKIP=()
_MODULE_FAIL=()

_is_root() { [ "$EUID" -eq 0 ]; }

# ---------------------------------------------------------------------------
# Module 1: Platform Power Monitoring
# ---------------------------------------------------------------------------
setup_powercap() {
    local MODULE="Platform Power Monitoring"
    echo ""
    echo "--- $MODULE ---"

    if ! _is_root; then
        echo "  [SKIP] Root required. Re-run with sudo to configure this module."
        _MODULE_SKIP+=("$MODULE")
        return 0
    fi

    # Check if RAPL is available on this system
    local has_rapl=false
    local control_type
    for control_type in /sys/class/powercap/*; do
        [ -d "$control_type" ] && has_rapl=true && break
    done
    if [ "$has_rapl" = false ]; then
        echo "  [WARN] No powercap devices detected (RAPL may not be supported on this system)"
        _MODULE_SKIP+=("$MODULE (no RAPL files)")
        return 0
    fi

    # Remove stale sysfsutils config from the old group-based approach.
    # That config (generated by setup-powercap-permissions.sh) sets mode 0440 at boot
    # via sysfsutils.service, which runs AFTER udev and overrides the udev chmod o+r,
    # leaving the main zone energy_uj file at 0440 (not world-readable).
    if [ -f /etc/sysfs.d/powercap.conf ]; then
        rm -f /etc/sysfs.d/powercap.conf
        echo "  [OK] Removed stale /etc/sysfs.d/powercap.conf (old group-based config)"
    fi

    # Write udev rule — fires at actual boot when the kernel generates real 'add' events
    # for powercap devices (persistent, no group membership or logout required).
    # Note: udevadm trigger (synthetic events) cannot activate RUN+= for intel-rapl zone
    # devices because their sysfs uevent file is kernel-write-protected even for root.
    # Real kernel boot events are NOT affected by this restriction.
    local UDEV_RULE_FILE="/etc/udev/rules.d/90-powercap.rules"
    mkdir -p /etc/udev/rules.d
    cat > "$UDEV_RULE_FILE" << 'UDEV_EOF'
# RAPL powercap energy counter read access - auto-generated by system-setup.sh
# Grants all users read-only access to energy_uj counters on each boot.
SUBSYSTEM=="powercap", ATTR{energy_uj}!="", ACTION=="add", RUN+="/bin/chmod o+r /sys%p/energy_uj"
UDEV_EOF
    udevadm control --reload-rules 2>/dev/null || true
    echo "  [OK] udev rule written to $UDEV_RULE_FILE (active on every boot)"

    # Apply permissions to the current session immediately via direct chmod.
    # udevadm trigger cannot synthesize 'add' events for intel-rapl zone devices
    # (their uevent sysfs files are kernel-write-protected), so chmod directly instead.
    # /sys/class/powercap/*/energy_uj covers all zones via the flat class symlinks.
    # Uses shell glob because find does not traverse sysfs correctly.
    local energy_file chmod_count=0
    for energy_file in /sys/class/powercap/*/energy_uj; do
        [ -e "$energy_file" ] || continue
        if chmod o+r "$energy_file" 2>/dev/null; then
            chmod_count=$((chmod_count + 1))
        fi
    done
    if [ "$chmod_count" -gt 0 ]; then
        echo "  [OK] Permissions applied to $chmod_count energy_uj file(s) in current session"
    else
        echo "  [WARN] Could not apply permissions to any energy_uj files"
    fi

    # Verify access as the calling user
    local FIRST_FILE=""
    local control_type2 pattern2
    for control_type2 in /sys/class/powercap/*; do
        [ ! -d "$control_type2" ] && continue
        for pattern2 in "$control_type2"/*/energy_uj "$control_type2"/*/*/energy_uj; do
            [ ! -e "$pattern2" ] && continue
            case "$pattern2" in */device/* | */subsystem/*) continue ;; esac
            FIRST_FILE="$pattern2"
            break 2
        done
    done

    if [ -n "$FIRST_FILE" ]; then
        local CALLING_USER="${SUDO_USER:-}"
        if [ -n "$CALLING_USER" ]; then
            if sudo -u "$CALLING_USER" test -r "$FIRST_FILE" 2>/dev/null; then
                echo "  [OK] Powercap files are readable by '$CALLING_USER' without root"
            else
                echo "  [WARN] Verification failed for '$CALLING_USER'"
                echo "         Verify manually: cat $FIRST_FILE"
            fi
        else
            if test -r "$FIRST_FILE" 2>/dev/null; then
                echo "  [OK] Powercap files are readable without root"
            fi
        fi
    fi

    _MODULE_PASS+=("$MODULE")
}


# ---------------------------------------------------------------------------
# Module 2: Memory DIMM Information
# ---------------------------------------------------------------------------
setup_memory_dimm() {
    local MODULE="Memory DIMM Information"
    echo ""
    echo "--- $MODULE ---"

    if ! _is_root; then
        echo "  [SKIP] Root required. Re-run with sudo to configure this module."
        _MODULE_SKIP+=("$MODULE")
        return 0
    fi

    # Verify required tools
    local tool MISSING_TOOLS=false
    for tool in setcap getcap; do
        if ! command -v "$tool" > /dev/null 2>&1; then
            echo "  [ERROR] '$tool' not found. Install: sudo apt-get install libcap2-bin"
            MISSING_TOOLS=true
        fi
    done
    if [ "$MISSING_TOOLS" = true ]; then
        _MODULE_FAIL+=("$MODULE (install libcap2-bin and dmidecode, then re-run)")
        return 1
    fi

    # Locate dmidecode
    local DMIDECODE_PATH="" candidate
    for candidate in /usr/sbin/dmidecode /sbin/dmidecode /usr/bin/dmidecode; do
        if [ -x "$candidate" ]; then
            DMIDECODE_PATH="$candidate"
            break
        fi
    done
    [ -z "$DMIDECODE_PATH" ] && DMIDECODE_PATH=$(command -v dmidecode 2>/dev/null || true)
    if [ -z "$DMIDECODE_PATH" ]; then
        echo "  [ERROR] dmidecode not found. Install: sudo apt-get install dmidecode"
        _MODULE_FAIL+=("$MODULE (install dmidecode, then re-run)")
        return 1
    fi
    echo "  [OK] Found dmidecode at: $DMIDECODE_PATH"

    # Check existing capability
    local CURRENT_CAPS NEW_CAPS
    CURRENT_CAPS=$(getcap "$DMIDECODE_PATH" 2>/dev/null || true)
    if printf '%s' "$CURRENT_CAPS" | grep -q "cap_dac_read_search"; then
        echo "  [OK] cap_dac_read_search already set: $CURRENT_CAPS"
    fi

    # Apply capability
    setcap cap_dac_read_search+ep "$DMIDECODE_PATH" || { echo "  [ERROR] setcap failed"; _MODULE_FAIL+=("$MODULE"); return 1; }
    NEW_CAPS=$(getcap "$DMIDECODE_PATH" 2>/dev/null || true)
    echo "  [OK] Capability applied: $NEW_CAPS"
    echo "  [NOTE] Re-run this script after dmidecode package updates (upgrades reset capabilities)"

    # Verify
    local CALLING_USER="${SUDO_USER:-}"
    if [ -n "$CALLING_USER" ]; then
        if sudo -u "$CALLING_USER" "$DMIDECODE_PATH" -t 16,17 > /dev/null 2>&1; then
            echo "  [OK] dmidecode can read memory DIMM information without root"
        else
            echo "  [WARN] Verification failed for '$CALLING_USER' (AppArmor/SELinux may restrict access)"
            echo "         Verify manually: dmidecode -t 16,17"
        fi
    else
        if "$DMIDECODE_PATH" -t 16,17 > /dev/null 2>&1; then
            echo "  [OK] dmidecode can read memory DIMM information without root"
        else
            echo "  [WARN] Verification failed. Try: dmidecode -t 16,17"
        fi
    fi

    _MODULE_PASS+=("$MODULE")
}

# ---------------------------------------------------------------------------
# Module 3: GPU Engine Performance Metrics (perf_event_paranoid)
# ---------------------------------------------------------------------------
setup_gpu_perf_events() {
    local MODULE="GPU Engine Performance Metrics"
    echo ""
    echo "--- $MODULE ---"

    if ! _is_root; then
        echo "  [SKIP] Root required. Re-run with sudo to configure this module."
        _MODULE_SKIP+=("$MODULE")
        return 0
    fi

    # perf_event_paranoid controls which users can open Linux perf events.
    # The xe and i915 GPU drivers expose per-engine utilisation counters
    # (engine-active-ticks / engine-total-ticks) via their device PMU.
    # These events measure system-wide GPU state and always use pid=-1
    # (system-wide mode), which requires perf_event_paranoid <= 0.
    #
    # Paranoia levels:
    #   -1  No restrictions (not recommended)
    #    0  Hardware/device PMU events for all users, including system-wide
    #       (xe/i915 GPU engine utilisation requires this level)
    #       Kernel-space tracing is still restricted to root/CAP_PERFMON.
    #    1  Per-process software events only for unprivileged users
    #       (NOT sufficient for system-wide GPU device PMU events)
    #    2  Software events only (many distro defaults)
    #    3+ Block tracing / eBPF helpers (Ubuntu hardened default; value 4 on some)
    #
    # Setting 0 is used by Fedora workstation defaults and allows xe/i915 GPU
    # engine PMU access without enabling the more security-sensitive kernel-space
    # tracing or sampling capabilities.
    #
    # Additionally, the i915 and xe drivers expose per-driver paranoia knobs
    # that gate the OA / observation perf streams used by intel_gpu_top and
    # qmmd for unprivileged metric collection:
    #   dev.i915.perf_stream_paranoid = 0
    #   dev.xe.observation_paranoid   = 0
    local TARGET_PARANOID=0
    local SYSCTL_FILE="/etc/sysctl.d/90-esq-perf.conf"

    # Check current values
    local CURRENT_PARANOID CURRENT_I915 CURRENT_XE
    CURRENT_PARANOID=$(cat /proc/sys/kernel/perf_event_paranoid 2>/dev/null || echo "unknown")
    CURRENT_I915=$(cat /proc/sys/dev/i915/perf_stream_paranoid 2>/dev/null || echo "absent")
    CURRENT_XE=$(cat /proc/sys/dev/xe/observation_paranoid 2>/dev/null || echo "absent")
    echo "  [INFO] kernel.perf_event_paranoid       = $CURRENT_PARANOID (need <= 0)"
    echo "  [INFO] dev.i915.perf_stream_paranoid   = $CURRENT_I915 (need 0; 'absent' = i915 not loaded)"
    echo "  [INFO] dev.xe.observation_paranoid     = $CURRENT_XE (need 0; 'absent' = xe not loaded)"

    # Write sysctl.d drop-in for persistence across reboots.
    # Uses a drop-in under /etc/sysctl.d/ so it survives package upgrades.
    mkdir -p /etc/sysctl.d
    cat > "$SYSCTL_FILE" << 'SYSCTL_EOF'
# GPU engine-level performance metrics via Linux perf PMU
# Required for xe/i915 engine-active-ticks / engine-total-ticks events.
# These GPU device PMU events use system-wide (pid=-1) mode and require
# perf_event_paranoid <= 0 for unprivileged access.
# Value 0: system-wide hardware/device PMU events for all users;
#          kernel-space tracing still requires root/CAP_PERFMON.
# The two dev.* keys gate the i915 OA / xe observation perf streams
# consumed by intel_gpu_top and qmmd.
# Auto-generated by system-setup.sh — do not edit manually.
kernel.perf_event_paranoid = 0
dev.i915.perf_stream_paranoid = 0
dev.xe.observation_paranoid = 0
SYSCTL_EOF
    echo "  [OK] Wrote persistent config: $SYSCTL_FILE"

    # Apply to the current session (per-key so a missing driver knob does
    # not fail the module; sysctl -w errors on absent keys, sysctl.d does not).
    local applied=0 skipped=0
    if sysctl -w kernel.perf_event_paranoid="$TARGET_PARANOID" > /dev/null 2>&1; then
        applied=$((applied + 1))
    else
        echo "  [WARN] sysctl write failed for kernel.perf_event_paranoid"
        _MODULE_FAIL+=("$MODULE (perf_event_paranoid write failed)")
        return 1
    fi
    if [ -f /proc/sys/dev/i915/perf_stream_paranoid ]; then
        if sysctl -w dev.i915.perf_stream_paranoid="$TARGET_PARANOID" > /dev/null 2>&1; then
            applied=$((applied + 1))
        fi
    else
        skipped=$((skipped + 1))
    fi
    if [ -f /proc/sys/dev/xe/observation_paranoid ]; then
        if sysctl -w dev.xe.observation_paranoid="$TARGET_PARANOID" > /dev/null 2>&1; then
            applied=$((applied + 1))
        fi
    else
        skipped=$((skipped + 1))
    fi
    echo "  [OK] Applied $applied paranoid knob(s) to current session ($skipped driver(s) not loaded)"

    # Verify: try to open a xe or i915 PMU file descriptor as the calling user.
    local CALLING_USER="${SUDO_USER:-}"
    local pmu_type_file
    # Look for the first xe PMU, fall back to i915
    for pmu_type_file in /sys/bus/event_source/devices/xe_*/type \
                         /sys/bus/event_source/devices/i915/type; do
        [ -f "$pmu_type_file" ] && break
    done

    if [ ! -f "$pmu_type_file" ]; then
        echo "  [INFO] No Intel GPU PMU devices found on this system"
        echo "         (xe/i915 GPU driver not loaded or no Intel GPU present)"
        _MODULE_PASS+=("$MODULE (no GPU PMU on this system)")
        return 0
    fi

    # Quick functional test: try perf stat with the discovered PMU type.
    # Use 'perf stat -e {type}/event=0x1/' for a single sample.
    local PMU_NAME
    PMU_NAME=$(basename "$(dirname "$pmu_type_file")")
    if [ -n "$CALLING_USER" ]; then
        if sudo -u "$CALLING_USER" perf stat -e "${PMU_NAME}/event=0x1/" \
                -a sleep 0 > /dev/null 2>&1; then
            echo "  [OK] GPU PMU events accessible as '$CALLING_USER' (${PMU_NAME})"
        else
            echo "  [INFO] perf functional test inconclusive for '$CALLING_USER'"
            echo "         Verify manually: perf stat -e ${PMU_NAME}/event=0x1/ sleep 0"
        fi
    else
        if perf stat -e "${PMU_NAME}/event=0x1/" -a sleep 0 > /dev/null 2>&1; then
            echo "  [OK] GPU PMU events accessible (${PMU_NAME})"
        else
            echo "  [INFO] perf functional test inconclusive"
            echo "         Verify manually: perf stat -e ${PMU_NAME}/event=0x1/ sleep 0"
        fi
    fi

    _MODULE_PASS+=("$MODULE")
}

# ---------------------------------------------------------------------------
# Module 4: Telemetry APT Packages (fw_sys_telemetry build/runtime deps)
# ---------------------------------------------------------------------------
# Build deps for cargo/qmmd, runtime fetchers, GPU tools, and perf for qmmd.
# Packages installed by apt persist across reboots naturally.
setup_telemetry_apt_packages() {
    local MODULE="Telemetry APT Packages"
    echo ""
    echo "--- $MODULE ---"

    if ! _is_root; then
        echo "  [SKIP] Root required. Re-run with sudo to configure this module."
        _MODULE_SKIP+=("$MODULE")
        return 0
    fi

    if ! command -v apt-get > /dev/null 2>&1; then
        echo "  [SKIP] apt-get not found (non-Debian host); install equivalents manually."
        _MODULE_SKIP+=("$MODULE (no apt-get)")
        return 0
    fi

    local pkgs=(
        build-essential
        pkg-config
        libssl-dev
        libdrm-dev
        git
        curl
        ca-certificates
        intel-gpu-tools
        "linux-tools-$(uname -r)"
        linux-tools-generic
    )

    DEBIAN_FRONTEND=noninteractive apt-get update -qq || true
    if DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${pkgs[@]}"; then
        echo "  [OK] Installed telemetry APT packages (${#pkgs[@]} packages)"
        _MODULE_PASS+=("$MODULE")
    else
        echo "  [ERROR] apt-get install failed for one or more telemetry packages"
        _MODULE_FAIL+=("$MODULE")
        return 1
    fi
}

# ---------------------------------------------------------------------------
# Module 5: Telemetry Kernel Modules
# ---------------------------------------------------------------------------
# Loads kernel modules used by CPU / NPU / GPU telemetry collectors and
# persists them via /etc/modules-load.d/ so they auto-load every boot.
setup_telemetry_kernel_modules() {
    local MODULE="Telemetry Kernel Modules"
    echo ""
    echo "--- $MODULE ---"

    if ! _is_root; then
        echo "  [SKIP] Root required. Re-run with sudo to configure this module."
        _MODULE_SKIP+=("$MODULE")
        return 0
    fi

    local mods=(coretemp intel_rapl_common intel_rapl_msr intel_pmt_telemetry intel_vpu)
    local m load_failed=()
    for m in "${mods[@]}"; do
        if lsmod | awk '{print $1}' | grep -qx "$m"; then
            echo "  [OK] $m already loaded"
            continue
        fi
        if modprobe "$m" 2>/dev/null; then
            echo "  [OK] modprobe $m"
        else
            echo "  [WARN] modprobe $m failed (module may not be available on this kernel)"
            load_failed+=("$m")
        fi
    done

    # Persist module list so they auto-load every boot.
    local conf=/etc/modules-load.d/esq-telemetry.conf
    mkdir -p /etc/modules-load.d
    if printf '%s\n' "${mods[@]}" > "$conf" 2>/dev/null; then
        echo "  [OK] Persisted module list in $conf (loads on every boot)"
    else
        echo "  [WARN] Could not write $conf"
    fi

    if [ "${#load_failed[@]}" -gt 0 ]; then
        _MODULE_PASS+=("$MODULE (some modules unavailable: ${load_failed[*]})")
    else
        _MODULE_PASS+=("$MODULE")
    fi
}

# ---------------------------------------------------------------------------
# Module 6: debugfs Mount (required by npu-monitor-tool)
# ---------------------------------------------------------------------------
# Mounts debugfs immediately and adds an /etc/fstab entry so the mount
# survives reboot. (Most distros mount debugfs by default, but several
# minimal/server images do not.)
setup_debugfs() {
    local MODULE="debugfs Mount"
    echo ""
    echo "--- $MODULE ---"

    if ! _is_root; then
        echo "  [SKIP] Root required. Re-run with sudo to configure this module."
        _MODULE_SKIP+=("$MODULE")
        return 0
    fi

    if mountpoint -q /sys/kernel/debug; then
        echo "  [OK] /sys/kernel/debug already mounted"
    else
        if mount -t debugfs none /sys/kernel/debug 2>/dev/null; then
            echo "  [OK] Mounted debugfs on /sys/kernel/debug"
        else
            echo "  [ERROR] Failed to mount debugfs"
            _MODULE_FAIL+=("$MODULE")
            return 1
        fi
    fi

    # Persist via /etc/fstab so the mount survives reboot.
    local fstab_line="debugfs /sys/kernel/debug debugfs defaults 0 0"
    if grep -qE '^[[:space:]]*[^#].*[[:space:]]/sys/kernel/debug[[:space:]]' /etc/fstab 2>/dev/null; then
        echo "  [OK] /etc/fstab already has a /sys/kernel/debug entry"
    else
        if printf '\n# Added by system-setup.sh for fw_sys_telemetry (npu-monitor-tool)\n%s\n' \
                "$fstab_line" >> /etc/fstab; then
            echo "  [OK] Added debugfs entry to /etc/fstab (mounts on every boot)"
        else
            echo "  [WARN] Could not append to /etc/fstab"
        fi
    fi

    # Traversal-only widening so the opt-in upstream NPU monitor tool
    # can read /sys/kernel/debug/accel/<pci>/fw_version. Individual
    # debugfs entries stay 0444 root:root; we never recurse.
    if [ -d /sys/kernel/debug/accel ]; then
        if chmod o+x /sys/kernel/debug 2>/dev/null \
           && chmod o+rx /sys/kernel/debug/accel 2>/dev/null; then
            echo "  [OK] Granted unprivileged traversal of /sys/kernel/debug/accel"
        else
            echo "  [WARN] Could not chmod debugfs traversal (NPU monitor tool may need it)"
        fi
    fi

    _MODULE_PASS+=("$MODULE")
}

# ---------------------------------------------------------------------------
# Module 7: Rust Toolchain (per-user, for qmmd build)
# ---------------------------------------------------------------------------
# Bootstraps rustup for the calling (non-root) user. Installs to ~/.cargo
# which persists across reboots without any system-wide modification.
setup_rust_toolchain() {
    local MODULE="Rust Toolchain"
    echo ""
    echo "--- $MODULE ---"

    local CALLING_USER="${SUDO_USER:-$USER}"
    if [ -z "$CALLING_USER" ] || [ "$CALLING_USER" = "root" ]; then
        echo "  [SKIP] Cannot bootstrap rustup for the root user; install Rust per-user manually."
        _MODULE_SKIP+=("$MODULE (no non-root calling user)")
        return 0
    fi

    if sudo -u "$CALLING_USER" -H bash -lc 'command -v cargo' > /dev/null 2>&1; then
        local cargo_path
        cargo_path=$(sudo -u "$CALLING_USER" -H bash -lc 'command -v cargo')
        echo "  [OK] cargo already present at $cargo_path"
        _MODULE_PASS+=("$MODULE")
        return 0
    fi

    if ! command -v curl > /dev/null 2>&1; then
        echo "  [ERROR] curl not available; ensure Module 4 (Telemetry APT Packages) ran first."
        _MODULE_FAIL+=("$MODULE (curl missing)")
        return 1
    fi

    echo "  [INFO] Bootstrapping rustup for '$CALLING_USER' (installs to ~/.cargo)..."
    if sudo -u "$CALLING_USER" -H bash -lc \
            'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | \
             sh -s -- -y --default-toolchain stable --profile minimal' > /dev/null 2>&1; then
        echo "  [OK] rustup + stable toolchain installed for '$CALLING_USER'"
        _MODULE_PASS+=("$MODULE")
    else
        echo "  [ERROR] rustup install failed for '$CALLING_USER'"
        _MODULE_FAIL+=("$MODULE")
        return 1
    fi
}

# ---------------------------------------------------------------------------
# Module 8: xpu-smi (Intel Data Center GPU tooling, dGPU power/bandwidth)
# ---------------------------------------------------------------------------
# Best-effort apt install; xpu-smi is important for dGPU utilisation and
# power telemetry but is not in the default Ubuntu repos on every image.
# When unavailable the script reports SKIP and the user can add the Intel
# GPU repository per Intel's docs.
setup_xpu_smi() {
    local MODULE="xpu-smi (dGPU telemetry)"
    echo ""
    echo "--- $MODULE ---"

    if command -v xpu-smi > /dev/null 2>&1; then
        echo "  [OK] xpu-smi already on PATH ($(command -v xpu-smi))"
        _MODULE_PASS+=("$MODULE")
        return 0
    fi

    if ! _is_root; then
        echo "  [SKIP] Root required. Re-run with sudo to configure this module."
        _MODULE_SKIP+=("$MODULE")
        return 0
    fi

    if ! command -v apt-get > /dev/null 2>&1; then
        echo "  [SKIP] apt-get not found; install xpu-smi per Intel Data Center GPU docs."
        _MODULE_SKIP+=("$MODULE (no apt-get)")
        return 0
    fi

    if DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends xpu-smi 2>/dev/null; then
        echo "  [OK] Installed xpu-smi"
        _MODULE_PASS+=("$MODULE")
    else
        echo "  [SKIP] xpu-smi not in configured apt repos."
        echo "         Add the Intel Data Center GPU repository, then re-run this script."
        echo "         Docs: https://dgpu-docs.intel.com/driver/installation.html"
        _MODULE_SKIP+=("$MODULE (not in apt repos)")
    fi
}

# ---------------------------------------------------------------------------
# Module 9: NPU PMT Telemetry Read Access
# ---------------------------------------------------------------------------
# Grants world-read on /sys/class/intel_pmt/telem*/telem (default
# 0440 root:root) via a persistent udev rule + immediate chmod, so
# the NPU collector can decode VPU energy/frequency/utilisation.
setup_pmt_telemetry() {
    local MODULE="NPU PMT Telemetry Read Access"
    echo ""
    echo "--- $MODULE ---"

    if ! _is_root; then
        echo "  [SKIP] Root required. Re-run with sudo to configure this module."
        _MODULE_SKIP+=("$MODULE")
        return 0
    fi

    if [ ! -d /sys/class/intel_pmt ]; then
        echo "  [INFO] /sys/class/intel_pmt not present (intel_pmt_telemetry driver"
        echo "         not loaded or unsupported on this platform)."
        _MODULE_SKIP+=("$MODULE (no /sys/class/intel_pmt)")
        return 0
    fi

    # ATTR{telem}!="" filters out crashlog-only PMT entries.
    local UDEV_RULE_FILE="/etc/udev/rules.d/91-intel-pmt.rules"
    mkdir -p /etc/udev/rules.d
    cat > "$UDEV_RULE_FILE" << 'UDEV_EOF'
# Intel PMT telemetry read access - auto-generated by system-setup.sh
# Grants all users read-only access to PMT telem blobs on each boot.
SUBSYSTEM=="intel_pmt", ATTR{telem}!="", ACTION=="add", RUN+="/bin/chmod o+r /sys%p/telem"
UDEV_EOF
    udevadm control --reload-rules 2>/dev/null || true
    echo "  [OK] udev rule written to $UDEV_RULE_FILE (active on every boot)"

    # Apply to the current session via direct chmod (udev synthetic
    # triggers on sysfs class entries are kernel-write-protected).
    local telem_file chmod_count=0
    for telem_file in /sys/class/intel_pmt/telem*/telem; do
        [ -e "$telem_file" ] || continue
        # Resolve the symlink so chmod hits the real sysfs node.
        local target
        target=$(readlink -f "$telem_file" 2>/dev/null || echo "$telem_file")
        if chmod o+r "$target" 2>/dev/null; then
            chmod_count=$((chmod_count + 1))
        fi
    done
    if [ "$chmod_count" -gt 0 ]; then
        echo "  [OK] Permissions applied to $chmod_count PMT telem file(s) in current session"
    else
        echo "  [WARN] No PMT telem files found to chmod (kernel may emit them later)"
    fi

    # Verify access as the calling user.
    local FIRST_FILE=""
    local candidate
    for candidate in /sys/class/intel_pmt/telem*/telem; do
        [ -e "$candidate" ] && FIRST_FILE="$candidate" && break
    done
    if [ -n "$FIRST_FILE" ]; then
        local CALLING_USER="${SUDO_USER:-}"
        if [ -n "$CALLING_USER" ]; then
            if sudo -u "$CALLING_USER" test -r "$FIRST_FILE" 2>/dev/null; then
                echo "  [OK] PMT telem files are readable by '$CALLING_USER' without root"
            else
                echo "  [WARN] Verification failed for '$CALLING_USER'"
                echo "         Verify manually: cat $FIRST_FILE > /dev/null"
            fi
        fi
    fi

    _MODULE_PASS+=("$MODULE")
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
    echo "=== System Setup ==="
    echo "Running as: $CURRENT_USER"

    setup_powercap
    setup_memory_dimm
    setup_gpu_perf_events
    setup_telemetry_apt_packages
    setup_telemetry_kernel_modules
    setup_debugfs
    setup_rust_toolchain
    setup_xpu_smi
    setup_pmt_telemetry

    echo ""
    echo "=== Summary ==="
    local m
    if [ ${#_MODULE_PASS[@]} -gt 0 ]; then
        for m in "${_MODULE_PASS[@]}"; do echo "  [OK]   $m"; done
    fi
    if [ ${#_MODULE_SKIP[@]} -gt 0 ]; then
        for m in "${_MODULE_SKIP[@]}"; do echo "  [SKIP] $m"; done
    fi
    if [ ${#_MODULE_FAIL[@]} -gt 0 ]; then
        for m in "${_MODULE_FAIL[@]}"; do echo "  [FAIL] $m"; done
    fi
    echo ""
    if [ ${#_MODULE_FAIL[@]} -eq 0 ]; then
        echo "Setup complete."
    else
        echo "Setup complete with errors. Review the output above."
        return 1
    fi
}

main "$@"
