#!/bin/bash
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# System Setup
# Configures system settings required for full functionality.
# New modules can be added to this script without requiring documentation updates.
#
# Usage:
#   sudo bash system-setup.sh    Run all modules (recommended)
#   bash system-setup.sh         Run modules that do not require root

CURRENT_USER="${SUDO_USER:-$USER}"
_MODULE_PASS=()
_MODULE_SKIP=()
_MODULE_FAIL=()

_is_root() { [ "$EUID" -eq 0 ]; }

# ---------------------------------------------------------------------------
# Module 1: Platform Power Monitoring
# ---------------------------------------------------------------------------
setup_powercap() {
    local MODULE="Platform Power Monitoring"
    echo ""
    echo "--- $MODULE ---"

    if ! _is_root; then
        echo "  [SKIP] Root required. Re-run with sudo to configure this module."
        _MODULE_SKIP+=("$MODULE")
        return 0
    fi

    # Check if RAPL is available on this system
    local has_rapl=false
    local control_type
    for control_type in /sys/class/powercap/*; do
        [ -d "$control_type" ] && has_rapl=true && break
    done
    if [ "$has_rapl" = false ]; then
        echo "  [WARN] No powercap devices detected (RAPL may not be supported on this system)"
        _MODULE_SKIP+=("$MODULE (no RAPL files)")
        return 0
    fi

    # Remove stale sysfsutils config from the old group-based approach.
    # That config (generated by setup-powercap-permissions.sh) sets mode 0440 at boot
    # via sysfsutils.service, which runs AFTER udev and overrides the udev chmod o+r,
    # leaving the main zone energy_uj file at 0440 (not world-readable).
    if [ -f /etc/sysfs.d/powercap.conf ]; then
        rm -f /etc/sysfs.d/powercap.conf
        echo "  [OK] Removed stale /etc/sysfs.d/powercap.conf (old group-based config)"
    fi

    # Write udev rule — fires at actual boot when the kernel generates real 'add' events
    # for powercap devices (persistent, no group membership or logout required).
    # Note: udevadm trigger (synthetic events) cannot activate RUN+= for intel-rapl zone
    # devices because their sysfs uevent file is kernel-write-protected even for root.
    # Real kernel boot events are NOT affected by this restriction.
    local UDEV_RULE_FILE="/etc/udev/rules.d/90-powercap.rules"
    mkdir -p /etc/udev/rules.d
    cat > "$UDEV_RULE_FILE" << 'UDEV_EOF'
# RAPL powercap energy counter read access - auto-generated by system-setup.sh
# Grants all users read-only access to energy_uj counters on each boot.
SUBSYSTEM=="powercap", ATTR{energy_uj}!="", ACTION=="add", RUN+="/bin/chmod o+r /sys%p/energy_uj"
UDEV_EOF
    udevadm control --reload-rules 2>/dev/null || true
    echo "  [OK] udev rule written to $UDEV_RULE_FILE (active on every boot)"

    # Apply permissions to the current session immediately via direct chmod.
    # udevadm trigger cannot synthesize 'add' events for intel-rapl zone devices
    # (their uevent sysfs files are kernel-write-protected), so chmod directly instead.
    # /sys/class/powercap/*/energy_uj covers all zones via the flat class symlinks.
    # Uses shell glob because find does not traverse sysfs correctly.
    local energy_file chmod_count=0
    for energy_file in /sys/class/powercap/*/energy_uj; do
        [ -e "$energy_file" ] || continue
        if chmod o+r "$energy_file" 2>/dev/null; then
            chmod_count=$((chmod_count + 1))
        fi
    done
    if [ "$chmod_count" -gt 0 ]; then
        echo "  [OK] Permissions applied to $chmod_count energy_uj file(s) in current session"
    else
        echo "  [WARN] Could not apply permissions to any energy_uj files"
    fi

    # Verify access as the calling user
    local FIRST_FILE=""
    local control_type2 pattern2
    for control_type2 in /sys/class/powercap/*; do
        [ ! -d "$control_type2" ] && continue
        for pattern2 in "$control_type2"/*/energy_uj "$control_type2"/*/*/energy_uj; do
            [ ! -e "$pattern2" ] && continue
            case "$pattern2" in */device/* | */subsystem/*) continue ;; esac
            FIRST_FILE="$pattern2"
            break 2
        done
    done

    if [ -n "$FIRST_FILE" ]; then
        local CALLING_USER="${SUDO_USER:-}"
        if [ -n "$CALLING_USER" ]; then
            if sudo -u "$CALLING_USER" test -r "$FIRST_FILE" 2>/dev/null; then
                echo "  [OK] Powercap files are readable by '$CALLING_USER' without root"
            else
                echo "  [WARN] Verification failed for '$CALLING_USER'"
                echo "         Verify manually: cat $FIRST_FILE"
            fi
        else
            if test -r "$FIRST_FILE" 2>/dev/null; then
                echo "  [OK] Powercap files are readable without root"
            fi
        fi
    fi

    _MODULE_PASS+=("$MODULE")
}


# ---------------------------------------------------------------------------
# Module 2: Memory DIMM Information
# ---------------------------------------------------------------------------
setup_memory_dimm() {
    local MODULE="Memory DIMM Information"
    echo ""
    echo "--- $MODULE ---"

    if ! _is_root; then
        echo "  [SKIP] Root required. Re-run with sudo to configure this module."
        _MODULE_SKIP+=("$MODULE")
        return 0
    fi

    # Verify required tools
    local tool MISSING_TOOLS=false
    for tool in setcap getcap; do
        if ! command -v "$tool" > /dev/null 2>&1; then
            echo "  [ERROR] '$tool' not found. Install: sudo apt-get install libcap2-bin"
            MISSING_TOOLS=true
        fi
    done
    if [ "$MISSING_TOOLS" = true ]; then
        _MODULE_FAIL+=("$MODULE (install libcap2-bin and dmidecode, then re-run)")
        return 1
    fi

    # Locate dmidecode
    local DMIDECODE_PATH="" candidate
    for candidate in /usr/sbin/dmidecode /sbin/dmidecode /usr/bin/dmidecode; do
        if [ -x "$candidate" ]; then
            DMIDECODE_PATH="$candidate"
            break
        fi
    done
    [ -z "$DMIDECODE_PATH" ] && DMIDECODE_PATH=$(command -v dmidecode 2>/dev/null || true)
    if [ -z "$DMIDECODE_PATH" ]; then
        echo "  [ERROR] dmidecode not found. Install: sudo apt-get install dmidecode"
        _MODULE_FAIL+=("$MODULE (install dmidecode, then re-run)")
        return 1
    fi
    echo "  [OK] Found dmidecode at: $DMIDECODE_PATH"

    # Check existing capability
    local CURRENT_CAPS NEW_CAPS
    CURRENT_CAPS=$(getcap "$DMIDECODE_PATH" 2>/dev/null || true)
    if printf '%s' "$CURRENT_CAPS" | grep -q "cap_dac_read_search"; then
        echo "  [OK] cap_dac_read_search already set: $CURRENT_CAPS"
    fi

    # Apply capability
    setcap cap_dac_read_search+ep "$DMIDECODE_PATH" || { echo "  [ERROR] setcap failed"; _MODULE_FAIL+=("$MODULE"); return 1; }
    NEW_CAPS=$(getcap "$DMIDECODE_PATH" 2>/dev/null || true)
    echo "  [OK] Capability applied: $NEW_CAPS"
    echo "  [NOTE] Re-run this script after dmidecode package updates (upgrades reset capabilities)"

    # Verify
    local CALLING_USER="${SUDO_USER:-}"
    if [ -n "$CALLING_USER" ]; then
        if sudo -u "$CALLING_USER" "$DMIDECODE_PATH" -t 16,17 > /dev/null 2>&1; then
            echo "  [OK] dmidecode can read memory DIMM information without root"
        else
            echo "  [WARN] Verification failed for '$CALLING_USER' (AppArmor/SELinux may restrict access)"
            echo "         Verify manually: dmidecode -t 16,17"
        fi
    else
        if "$DMIDECODE_PATH" -t 16,17 > /dev/null 2>&1; then
            echo "  [OK] dmidecode can read memory DIMM information without root"
        else
            echo "  [WARN] Verification failed. Try: dmidecode -t 16,17"
        fi
    fi

    _MODULE_PASS+=("$MODULE")
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
    echo "=== System Setup ==="
    echo "Running as: $CURRENT_USER"

    setup_powercap
    setup_memory_dimm

    echo ""
    echo "=== Summary ==="
    local m
    if [ ${#_MODULE_PASS[@]} -gt 0 ]; then
        for m in "${_MODULE_PASS[@]}"; do echo "  [OK]   $m"; done
    fi
    if [ ${#_MODULE_SKIP[@]} -gt 0 ]; then
        for m in "${_MODULE_SKIP[@]}"; do echo "  [SKIP] $m"; done
    fi
    if [ ${#_MODULE_FAIL[@]} -gt 0 ]; then
        for m in "${_MODULE_FAIL[@]}"; do echo "  [FAIL] $m"; done
    fi
    echo ""
    if [ ${#_MODULE_FAIL[@]} -eq 0 ]; then
        echo "Setup complete."
    else
        echo "Setup complete with errors. Review the output above."
        return 1
    fi
}

main "$@"
