# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

"""
This file contains a placeholder version string for the package.

The version is automatically managed and updated by setuptools_scm during the build or installation process.
Do not edit this file manually; it will be overwritten.
"""
version = "0+unknown"
