# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

tiers:
  scalable_ai_graphics_media_hetero_52gb:
    name: "Scalable AI Graphics Media"
    priority: 1
    requirements:
      dgpu_min_vram_gb: 52.0
      dgpu_min_devices: 2

  scalable_ai_graphics_media_hetero_24gb:
    name: "Scalable AI Graphics Media"
    priority: 2
    requirements:
      dgpu_min_vram_gb: 24.0
      dgpu_max_vram_gb: 51.9
      dgpu_min_devices: 2

  scalable_ai_graphics_media_hetero_10gb:
    name: "Scalable AI Graphics Media"
    priority: 3
    requirements:
      dgpu_min_vram_gb: 10.0
      dgpu_max_vram_gb: 23.9
      dgpu_min_devices: 2

  scalable_ai_graphics_media_hetero:
    name: "Scalable AI Graphics Media"
    priority: 4
    requirements:
      dgpu_max_vram_gb: 9.9
      dgpu_min_devices: 2

  scalable_ai_graphics_media_52gb:
    name: "Scalable AI Graphics Media"
    priority: 5
    requirements:
      dgpu_min_vram_gb: 52.0
      dgpu_min_devices: 1
      dgpu_max_devices: 1

  scalable_ai_graphics_media_24gb:
    name: "Scalable AI Graphics Media"
    priority: 6
    requirements:
      dgpu_min_vram_gb: 24.0
      dgpu_max_vram_gb: 51.9
      dgpu_min_devices: 1
      dgpu_max_devices: 1

  scalable_ai_graphics_media_10gb:
    name: "Scalable AI Graphics Media"
    priority: 7
    requirements:
      dgpu_min_vram_gb: 10.0
      dgpu_max_vram_gb: 23.9
      dgpu_min_devices: 1
      dgpu_max_devices: 1

  scalable_ai_graphics_media:
    name: "Scalable AI Graphics Media"
    priority: 8
    requirements:
      dgpu_max_vram_gb: 9.9
      dgpu_min_devices: 1
      dgpu_max_devices: 1

  scalable_performance:
    name: "Scalable Performance"
    priority: 9
    requirements:
      cpu_xeon_required: true

  efficiency_optimized:
    name: "Efficiency Optimized"
    priority: 10
    requirements:
      cpu_ultra_mobile_required: true
      igpu_required: true

  mainstream:
    name: "Mainstream"
    priority: 11
    requirements:
      cpu_core_required: true
      cpu_entry_excluded: true
      igpu_required: true

  entry:
    name: "Entry"
    priority: 12
    requirements:
      cpu_entry_required: true
      igpu_required: true
